""" heapx: A Python wrapper for a C-based heap implementation. """

# Import and expose everything from the compiled extension.
from ._heapx import * # imports functions implemented in heapx.c

try:
  # _version.py will be generated by setuptools_scm into this file for sdist/wheel builds
  from ._version import version as __version__
except Exception: __version__ = "0+unknown"

# Public API listing
__all__ = [name for name in globals() if not name.startswith("_")]
