name: Sync to Public Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to public repository
        env:
          DESTINATION_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          git remote add public https://mukherjee08:$DESTINATION_TOKEN@github.com/mukherjee08/heapx.git
          git push public main --force
